set -g default-terminal "xterm-256color"
set -g window-status-separator '|'
set -g status-bg gray

set-option -g default-shell /bin/zsh

# custom shortcut
## multiple inuput
bind-key y set-window-option synchronize-panes

# set window name auto
set-option -g status-interval 5
set-option -g automatic-rename on
# tmux 2.3 이상 버전에서 경로의 마지막 부분(basename)만 표시
set-option -g automatic-rename-format '#{b:pane_current_path}'
